### PR TITLE
open keyboard when focus is on contenteditable element

### PR DESCRIPTION
**Pull request by 1u**
Hi Marko
Happy new year!

Great addon, thx. We use it on a infoscreen for [openki.net](https://alpha.openki.net/kiosk/events) kiosk-view. 
To check: This patch now opens the keyboard in the description-field on [this](https://alpha.openki.net/courses/propose) page which is a richtext editor, not an input-field... 
[Our source](https://github.com/schuel/hmmm)

Hope you can release v3 soon.

lep pozdrav 
von Zürich nach Marburg

### CODE REVIEW

**Comment by 1u** [comment]
To make it clearer: FxKeyboard now opens on most online rich-text editors, where before it didn't appear on any of them.
here are some examples (demos to test):
- [CKEditor](http://ckeditor.com/demo)
- [Calmly Writer](http://calmlywriter.com/online/)
- [tinyMCE](https://www.tinymce.com/)
- [textbox-io](https://textbox.io/wysiwyg-html-editor/)
- [contenttools](http://getcontenttools.com/demo)
- [summernote](http://summernote.org/examples/)

thx for your work

**Comment by MarZab** [comment]
Woah, this merge kind of got lost in the new years buzz.

Thanks for reminding me. Merged the fix. I would like to refactor the whole field detection but cant find the time.

I like your project - if you depend on FxKeyboard do feel free to expand it as needed. My development is staled until further notice.

**Comment by 1u** [comment]
Cool, you're welcome :)

Thx. ...We unfortunately have any spare time for more work, :( cause we work in our free time on Openki and we're very slow.

Why don't you release v3 on [mozilla](https://addons.mozilla.org/de/firefox/addon/fxkeyboard/)?

**Comment by MarZab** [comment]
Its not ready for when Mozilla ends XUL suport - and porting it to webextesions is not something I can take on in the near future.

**Comment by 1u** [comment]
Ok, when will this be? cant you just define the firefox-versions which will be supported?

And the current version (2.4.2.1) is not affected by this?

**Comment by MarZab** [comment]
Nope, Mozilla does not have a fixed timeline on those.
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

So I have no idea. And no, the current version is completely build on XUL as is 3.0, but version 3.0 could be ported to webextensions more easily.

But if you are basing your project on firefox and xul, something like Pale Moon might be usefull.

**Comment by 1u** [comment]
Thx for the mozilla link, didn't know about that topic...

... I still don't really understand, why it's an argument not to release v3 if it will be supported as long as the current version. right?

**Pull request merged**
